spring:
  application:
    name: sink-app



 
  cloud:
    stream:
     # kafka:
     #  binder:
     #     brokers: localhost:9092
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
       
   
server:
  port: 8088          
          